name: kotlin-boilerplate

services:

  kotlin-boilerplate-mongo:
    image: mongo:6.0
    container_name: kotlin-boilerplate-mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: kotlin-boilerplate
    expose:
      - 27017
    volumes:
      - kotlin-boilerplate-mongo-data:/data/db
    networks:
      - internal-network



  kotlin-boilerplate:
    container_name: kotlin-boilerplate
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - kotlin-boilerplate-mongo
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      internal-network:
        ipv4_address: 172.20.0.220


volumes:

  kotlin-boilerplate-mongo-data:

networks:
  internal-network:
    external: true
