
logstash:
  host: ${LOGSTASH_HOST:localhost}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kotlin-boilerplate
      username: root
      password: root
      authentication-database: admin
  rabbitmq:
    listener:
      acknowledge-mode: auto
    host: localhost
    username: guest
    password: guest
    port: 5672
    dynamic: true

logging:
  config: classpath:logback-prod.xml
